# Generated by Django 5.1 on 2024-08-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_remove_topic_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_hide',
            field=models.BooleanField(default=False),
        ),
    ]
