# Generated by Django 5.1 on 2024-08-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_entry_hide_topic_topic_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_hide',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_hide',
        ),
    ]
